### ISSUE TITLE
[bug]-html-jsx的情况下，使用中文，字挤压到一起了

### ISSUE THREAD

**Issue by cxqeric** [Bowen7/react-rough-fiber#7]
![image](https://github.com/user-attachments/assets/174ce403-17e9-4bec-8141-635add9e20f9)

DOM 的时候中英文都没问题，
jsx 的时候英文没问题，中文不对

**Comment by Bowen7** [comment]
Remove <RoughSVG> to validate if it's an issue with `react-rough-fiber`:
![image](https://github.com/user-attachments/assets/4a3941d0-4b26-4411-a229-d6c262569a59)

I guess it's because of the font, you can try to load a font that supports Chinese.
